---
- hosts: webservers
  become: true
  tasks:
  - name: Create multiple directories
  file: path={{item}} state=directory
  with_items:
  - '/home/ansible/dir1'
  - '/home/ansible/dir2'
  - '/home/ansible/dir3'
